openapi: '3.1.0'
info:
  title: MyClinic API
  version: '1.0'
paths:
  /api/get-patient:
    get:
      description: 患者番号をもとに患者情報を返す
      parameters:
        - in: query
          description: 患者番号
          name: patient-id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
  /api/save-patient-image:
    post:
      description: 患者画像をアップロードする
      parameters: 
        - in: query
          name: patient-id
          schema:
            type: integer
          required: true
          description: 患者番号
          example: 1234
        - in: query
          name: file-name
          schema:
            type: string
          required: true
          description: アップロード後のファイル名
          example: 1234-hokensho-20230211220932-01.jpg
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
              description: 画像データ
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                description: 成功（true）、失敗（false）
  /api/patient-image:
    get:
      description: 患者画像をダウンロードする
      parameters:
        - in: query
          name: patient-id
          schema:
            type: integer
          required: true
          description: 患者番号
          example: 1234
        - in: query
          name: file-name
          schema:
            type: string
          required: true
          description: アップロード後のファイル名
          example: 1234-hokensho-20230211220932-01.jpg
      responses:
        '200':
          description: Success
          content:
            image/*:
              schema:
                type: string
                format: binary
                description: 画像データ
components:
  schemas:
    Patient:
      description: 患者情報
      type: object
      properties:
        patientId:
          description: 患者番号
          type: integer
          example: 1234
        lastName:
          type: string
          example: 診療
        firstName:
          type: string
          example: 太郎
        lastNameYomi:
          type: string
          example: しんりょう
        firstNameYomi:
          type: string
          example: たろう
        sex:
          type: string
          enum: [M, F]
          example: M
        birthday:
          type: string
          format: date
        address:
          type: string
          example: 東京都
        phone:
          type: string
          example: 03-1234-5678


                  


