// 初回

export interface RyouyouKeikakushoShokaiData {
  'issue-year'?: string;
  'issue-month'?: string;
  'issue-day'?: string;
  'patient-name'?: string;
  'patient-sex-male'?: string;
  'patient-sex-female'?: string;
  'birthdate-gengou-meiji'?: string;
  'birthdate-gengou-taishou'?: string;
  'birthdate-gengou-shouwa'?: string;
  'birthdate-gengou-heisei'?: string;
  'birthdate-gengou-reiwa'?: string;
  'birthdate-nen'?: string;
  'birthdate-month'?: string;
  'birthdate-day'?: string;
  'disease-diabetes'?: string;
  'disease-hypertension'?: string;
  'disease-hyperlipidemia'?: string;
  'mokuhyou-体重-mark'?: boolean;
  'mokuhyou-体重'?: string;
  'mokuhyou-BMI-mark'?: boolean;
  'mokuhyou-BMI'?: string;
  'mokuhyou-BP-mark'?: boolean;
  'mokuhyou-bp'?: string;
  'mokuhyou-HbA1c-mark'?: boolean;
  'mokuhyou-BP'?: string;
  'mokuhyou-達成目標'?: string;
  'mokuhyou-行動目標'?: string;
  'juuten-食事-mark'?: boolean;
  'juuten-食事-摂取量を適正にする-mark'?: boolean;
  'juuten-食事-食塩・調味料を控える-mark'?: boolean;
  'juuten-食事-食物繊維の摂取を増やす-mark'?: boolean;
  'juuten-食事-外食の際の注意事項-mark'?: boolean;
  'juuten-食事-外食の際の注意事項'?: string;
  'juuten-食事-油を使った料理の摂取を減らす-mark'?: boolean;
  'juuten-食事-その他-mark'?: boolean;
  'juuten-食事-節酒-mark'?: boolean;
  'shokuji-食事-節酒'?: string;
  'shokuji-食事-節酒-回'?: string;
  'juuten-食事-間食-mark'?: boolean;
  'shokuji-食事-間食'?: string;
  'shokuji-食事-間食-回'?: string;
  'juuten-食事-食べ方-mark'?: boolean;
  'juuten-食事-食べ方'?: string;
  'juuten-食事-食事時間-mark'?: boolean;
  'juuten-運動-mark'?: boolean;
  'juuten-運動-種類-mark'?: boolean;
  'juuten-運動-種類'?: string;
  'juuten-運動-時間'?: string;
  'juuten-運動-頻度'?: string;
  'juuten-運動-強度-脈拍'?: string;
  'juuten-運動-強度-その他'?: string;
  'juuten-運動-活動量-mark'?: boolean;
  'juuten-運動-活動量'?: string;
  'juuten-運動-注意事項-mark'?: boolean;
  'juuten-運動-注意事項'?: string;
  'juuten-たばこ-mark'?: boolean;
  'juuten-たばこ-非喫煙者-mark'?: boolean;
  'juuten-たばこ-禁煙・節煙の有効性-mark'?: boolean;
  'juuten-たばこ-禁煙の実施補法等-mark'?: boolean;
  'juuten-shokuji-mark'?: boolean;
  'juuten-その他-仕事'?: string;
  'juuten-その他-余暇'?: string;
  'juuten-その他-睡眠の確保'?: string;
  'juuten-その他-減量'?: string;
  'juuten-その他-家庭での計測'?: string;
  'juuten-その他-その他-mark'?: boolean;
  'juuten-その他-その他'?: string;
  'kensa-採血日-月'?: string;
  'kensa-採血日-日'?: string;
  'kensa-総コレステロール-mark'?: boolean;
  'kensa-総コレステロール'?: string;
  'kensa-血糖-mark'?: boolean;
  'kensa-血糖-空腹時-mark'?: boolean;
  'kensa-血糖-随時-mark'?: boolean;
  'kensa-血糖-食後-mark'?: boolean;
  'kensa-血糖-食後'?: string;
  'kensa-中性脂肪-mark'?: boolean;
  'kensa-中性脂肪'?: string;
  'kensa-血糖-値'?: string;
  'kensa-ＨＤＬコレステロール-mark'?: boolean;
  'kensa-ＨＤＬコレステロール'?: string;
  'kensa-HbA1c'?: string;
  'kensa-ＬＤＬコレステロール-mark'?: boolean;
  'kensa-ＬＤＬコレステロール'?: string;
  'kensa-血液検査項目-その他-mark'?: boolean;
  'kensa-血液検査項目-その他'?: string;
  'kensa-栄養状態-mark'?: boolean;
  'kensa-その他-その他-mark'?: boolean;
  '医師氏名'?: string;
};

export function mkRyouyouKeikakuShokaiData(): RyouyouKeikakushoShokaiData {
  return {
    'issue-year': "",
    'issue-month': "",
    'issue-day': "",
    'patient-name': "",
    'patient-sex-male': "",
    'patient-sex-female': "",
    'birthdate-gengou-meiji': "",
    'birthdate-gengou-taishou': "",
    'birthdate-gengou-shouwa': "",
    'birthdate-gengou-heisei': "",
    'birthdate-gengou-reiwa': "",
    'birthdate-nen': "",
    'birthdate-month': "",
    'birthdate-day': "",
    'disease-diabetes': "",
    'disease-hypertension': "",
    'disease-hyperlipidemia': "",
    'mokuhyou-体重-mark': false,
    'mokuhyou-体重': "",
    'mokuhyou-BMI-mark': false,
    'mokuhyou-BMI': "",
    'mokuhyou-BP-mark': false,
    'mokuhyou-bp': "",
    'mokuhyou-HbA1c-mark': false,
    'mokuhyou-BP': "",
    'mokuhyou-達成目標': "",
    'mokuhyou-行動目標': "",
    'juuten-食事-mark': false,
    'juuten-食事-摂取量を適正にする-mark': false,
    'juuten-食事-食塩・調味料を控える-mark': false,
    'juuten-食事-食物繊維の摂取を増やす-mark': false,
    'juuten-食事-外食の際の注意事項-mark': false,
    'juuten-食事-外食の際の注意事項': "",
    'juuten-食事-油を使った料理の摂取を減らす-mark': false,
    'juuten-食事-その他-mark': false,
    'juuten-食事-節酒-mark': false,
    'shokuji-食事-節酒': "",
    'shokuji-食事-節酒-回': "",
    'juuten-食事-間食-mark': false,
    'shokuji-食事-間食': "",
    'shokuji-食事-間食-回': "",
    'juuten-食事-食べ方-mark': false,
    'juuten-食事-食べ方': "",
    'juuten-食事-食事時間-mark': false,
    'juuten-運動-mark': false,
    'juuten-運動-種類-mark': false,
    'juuten-運動-種類': "",
    'juuten-運動-時間': "",
    'juuten-運動-頻度': "",
    'juuten-運動-強度-脈拍': "",
    'juuten-運動-強度-その他': "",
    'juuten-運動-活動量-mark': false,
    'juuten-運動-活動量': "",
    'juuten-運動-注意事項-mark': false,
    'juuten-運動-注意事項': "",
    'juuten-たばこ-mark': false,
    'juuten-たばこ-非喫煙者-mark': false,
    'juuten-たばこ-禁煙・節煙の有効性-mark': false,
    'juuten-たばこ-禁煙の実施補法等-mark': false,
    'juuten-shokuji-mark': false,
    'juuten-その他-仕事': "",
    'juuten-その他-余暇': "",
    'juuten-その他-睡眠の確保': "",
    'juuten-その他-減量': "",
    'juuten-その他-家庭での計測': "",
    'juuten-その他-その他-mark': false,
    'juuten-その他-その他': "",
    'kensa-採血日-月': "",
    'kensa-採血日-日': "",
    'kensa-総コレステロール-mark': false,
    'kensa-総コレステロール': "",
    'kensa-血糖-mark': false,
    'kensa-血糖-空腹時-mark': false,
    'kensa-血糖-随時-mark': false,
    'kensa-血糖-食後-mark': false,
    'kensa-血糖-食後': "",
    'kensa-中性脂肪-mark': false,
    'kensa-中性脂肪': "",
    'kensa-血糖-値': "",
    'kensa-ＨＤＬコレステロール-mark': false,
    'kensa-ＨＤＬコレステロール': "",
    'kensa-HbA1c': "",
    'kensa-ＬＤＬコレステロール-mark': false,
    'kensa-ＬＤＬコレステロール': "",
    'kensa-血液検査項目-その他-mark': false,
    'kensa-血液検査項目-その他': "",
    'kensa-栄養状態-mark': false,
    'kensa-その他-その他-mark': false,
    '医師氏名': "",
  };
}

// 継続

export interface RyouyouKeikakushoKeizokuData {
  'issue-year'?: string;
  'issue-month'?: string;
  'issue-day'?: string;
  'issue-times'?: string;
  'patient-name'?: string;
  'patient-sex-male'?: string;
  'patient-sex-female'?: string;
  'birthdate-gengou-meiji'?: string;
  'birthdate-gengou-taishou'?: string;
  'birthdate-gengou-shouwa'?: string;
  'birthdate-gengou-heisei'?: string;
  'birthdate-gengou-reiwa'?: string;
  'birthdate-nen'?: string;
  'birthdate-month'?: string;
  'birthdate-day'?: string;
  'birthdate-age'?: string;
  'disease-diabetes'?: string;
  'disease-hypertension'?: string;
  'disease-hyperlipidemia'?: string;
  'mokuhyou-体重-mark'?: boolean;
  'mokuhyou-体重'?: string;
  'mokuhyou-BMI-mark'?: boolean;
  'mokuhyou-BMI'?: string;
  'mokuhyou-BP-mark'?: boolean;
  'mokuhyou-bp'?: string;
  'mokuhyou-HbA1c-mark'?: boolean;
  'mokuhyou-BP'?: string;
  'mokuhyou-目標達成状況'?: string;
  'mokuhyou-達成目標'?: string;
  'mokuhyou-行動目標'?: string;
  'juuten-食事-mark'?: boolean;
  'juuten-食事-指導の必要なし-mark'?: boolean;
  'juuten-食事-摂取量を適正にする-mark'?: boolean;
  'juuten-食事-食塩・調味料を控える-mark'?: boolean;
  'juuten-食事-食物繊維の摂取を増やす-mark'?: boolean;
  'juuten-食事-外食の際の注意事項-mark'?: boolean;
  'juuten-食事-外食の際の注意事項'?: string;
  'juuten-食事-油を使った料理の摂取を減らす-mark'?: boolean;
  'juuten-食事-その他-mark'?: boolean;
  'juuten-食事-節酒-mark'?: boolean;
  'shokuji-食事-節酒'?: string;
  'shokuji-食事-節酒-回'?: string;
  'juuten-食事-間食-mark'?: boolean;
  'shokuji-食事-間食'?: string;
  'shokuji-食事-間食-回'?: string;
  'juuten-食事-食べ方-mark'?: boolean;
  'juuten-食事-食べ方'?: string;
  'juuten-食事-食事時間-mark'?: boolean;
  'juuten-運動-mark'?: boolean;
  'juuten-運動-指導の必要なし-mark'?: boolean;
  'juuten-運動-種類-mark'?: boolean;
  'juuten-運動-種類'?: string;
  'juuten-運動-時間'?: string;
  'juuten-運動-頻度'?: string;
  'juuten-運動-強度-脈拍'?: string;
  'juuten-運動-強度-その他'?: string;
  'juuten-運動-活動量-mark'?: boolean;
  'juuten-運動-活動量'?: string;
  'juuten-運動-注意事項-mark'?: boolean;
  'juuten-運動-注意事項'?: string;
  'juuten-たばこ-mark'?: boolean;
  'juuten-たばこ-禁煙・節煙の有効性-mark'?: boolean;
  'juuten-たばこ-禁煙の実施補法等-mark'?: boolean;
  'juuten-shokuji-mark'?: boolean;
  'juuten-その他-仕事'?: string;
  'juuten-その他-余暇'?: string;
  'juuten-その他-睡眠の確保'?: string;
  'juuten-その他-減量'?: string;
  'juuten-その他-家庭での計測'?: string;
  'juuten-その他-その他-mark'?: boolean;
  'juuten-その他-その他'?: string;
  'kensa-採血日-月'?: string;
  'kensa-採血日-日'?: string;
  'kensa-総コレステロール-mark'?: boolean;
  'kensa-総コレステロール'?: string;
  'kensa-血糖-mark'?: boolean;
  'kensa-血糖-空腹時-mark'?: boolean;
  'kensa-血糖-随時-mark'?: boolean;
  'kensa-血糖-食後-mark'?: boolean;
  'kensa-血糖-食後'?: string;
  'kensa-中性脂肪-mark'?: boolean;
  'kensa-中性脂肪'?: string;
  'kensa-血糖-値'?: string;
  'kensa-ＨＤＬコレステロール-mark'?: boolean;
  'kensa-ＨＤＬコレステロール'?: string;
  'kensa-HbA1c'?: string;
  'kensa-ＬＤＬコレステロール-mark'?: boolean;
  'kensa-ＬＤＬコレステロール'?: string;
  'kensa-血液検査項目-その他-mark'?: boolean;
  'kensa-血液検査項目-その他'?: string;
  'kensa-栄養状態-mark'?: boolean;
  'kensa-その他-その他-mark'?: boolean;
  '医師氏名'?: string;
  '患者署名省略-mark'?: boolean;
};

export function mkRyouyouKeikakuKeizokuData(): RyouyouKeikakushoKeizokuData {
  return {
    'issue-year': "",
    'issue-month': "",
    'issue-day': "",
    'issue-times': "",
    'patient-name': "",
    'patient-sex-male': "",
    'patient-sex-female': "",
    'birthdate-gengou-meiji': "",
    'birthdate-gengou-taishou': "",
    'birthdate-gengou-shouwa': "",
    'birthdate-gengou-heisei': "",
    'birthdate-gengou-reiwa': "",
    'birthdate-nen': "",
    'birthdate-month': "",
    'birthdate-day': "",
    'birthdate-age': "",
    'disease-diabetes': "",
    'disease-hypertension': "",
    'disease-hyperlipidemia': "",
    'mokuhyou-体重-mark': false,
    'mokuhyou-体重': "",
    'mokuhyou-BMI-mark': false,
    'mokuhyou-BMI': "",
    'mokuhyou-BP-mark': false,
    'mokuhyou-bp': "",
    'mokuhyou-HbA1c-mark': false,
    'mokuhyou-BP': "",
    'mokuhyou-目標達成状況': "",
    'mokuhyou-達成目標': "",
    'mokuhyou-行動目標': "",
    'juuten-食事-mark': false,
    'juuten-食事-指導の必要なし-mark': false,
    'juuten-食事-摂取量を適正にする-mark': false,
    'juuten-食事-食塩・調味料を控える-mark': false,
    'juuten-食事-食物繊維の摂取を増やす-mark': false,
    'juuten-食事-外食の際の注意事項-mark': false,
    'juuten-食事-外食の際の注意事項': "",
    'juuten-食事-油を使った料理の摂取を減らす-mark': false,
    'juuten-食事-その他-mark': false,
    'juuten-食事-節酒-mark': false,
    'shokuji-食事-節酒': "",
    'shokuji-食事-節酒-回': "",
    'juuten-食事-間食-mark': false,
    'shokuji-食事-間食': "",
    'shokuji-食事-間食-回': "",
    'juuten-食事-食べ方-mark': false,
    'juuten-食事-食べ方': "",
    'juuten-食事-食事時間-mark': false,
    'juuten-運動-mark': false,
    'juuten-運動-指導の必要なし-mark': false,
    'juuten-運動-種類-mark': false,
    'juuten-運動-種類': "",
    'juuten-運動-時間': "",
    'juuten-運動-頻度': "",
    'juuten-運動-強度-脈拍': "",
    'juuten-運動-強度-その他': "",
    'juuten-運動-活動量-mark': false,
    'juuten-運動-活動量': "",
    'juuten-運動-注意事項-mark': false,
    'juuten-運動-注意事項': "",
    'juuten-たばこ-mark': false,
    'juuten-たばこ-禁煙・節煙の有効性-mark': false,
    'juuten-たばこ-禁煙の実施補法等-mark': false,
    'juuten-shokuji-mark': false,
    'juuten-その他-仕事': "",
    'juuten-その他-余暇': "",
    'juuten-その他-睡眠の確保': "",
    'juuten-その他-減量': "",
    'juuten-その他-家庭での計測': "",
    'juuten-その他-その他-mark': false,
    'juuten-その他-その他': "",
    'kensa-採血日-月': "",
    'kensa-採血日-日': "",
    'kensa-総コレステロール-mark': false,
    'kensa-総コレステロール': "",
    'kensa-血糖-mark': false,
    'kensa-血糖-空腹時-mark': false,
    'kensa-血糖-随時-mark': false,
    'kensa-血糖-食後-mark': false,
    'kensa-血糖-食後': "",
    'kensa-中性脂肪-mark': false,
    'kensa-中性脂肪': "",
    'kensa-血糖-値': "",
    'kensa-ＨＤＬコレステロール-mark': false,
    'kensa-ＨＤＬコレステロール': "",
    'kensa-HbA1c': "",
    'kensa-ＬＤＬコレステロール-mark': false,
    'kensa-ＬＤＬコレステロール': "",
    'kensa-血液検査項目-その他-mark': false,
    'kensa-血液検査項目-その他': "",
    'kensa-栄養状態-mark': false,
    'kensa-その他-その他-mark': false,
    '医師氏名': "",
    '患者署名省略-mark': false,
  };
}