export interface RyouyouKeikakushoData {
  "issue-year": string;
  "issue-month": string;
  "issue-day": string;
  "patient-name": string;
  "patient-sex-male": string;
  "patient-sex-female": string;
  "birthdate-gengou-meiji": string;
  "birthdate-gengou-taishou": string;
  "birthdate-gengou-shouwa": string;
  "birthdate-gengou-heisei": string;
  "birthdate-gengou-reiwa": string;
  "birthdate-nen": string;
  "birthdate-month": string;
  "birthdate-day": string;
  "patient-age": string;
  "disease-diabetes": string;
  "disease-hypertension": string;
  "disease-hyperlipidemia": string;
  "mokuhyou-体重-mark": string;
  "mokuhyou-体重": string;
  "mokuhyou-BMI-mark": string;
  "mokuhyou-BMI": string;
  "mokuhyou-BP-mark": string;
  "mokuhyou-BP": string;
  "mokuhyou-HbA1c-mark": string;
  "mokuhyou-HbA1c": string;
  "mokuhyou-達成目標": string;
  "mokuhyou-行動目標": string;
  "juuten-食事-mark": string;
  "juuten-食事-摂取量を適正にする-mark": string;
  "juuten-食事-食塩・調味料を控える-mark": string;
  "juuten-食事-食物繊維の摂取を増やす-mark": string;
  "juuten-食事-外食の際の注意事項-mark": string;
  "juuten-食事-外食の際の注意事項": string;
  "juuten-食事-油を使った料理の摂取を減らす-mark": string;
  "juuten-食事-その他-mark": string;
  "juuten-食事-節酒-mark": string;
  "juuten-食事-節酒": string;
  "juuten-食事-節酒-回": string;
  "juuten-食事-間食-mark": string;
  "juuten-食事-間食": string;
  "juuten-食事-間食-回": string;
  "juuten-食事-食べ方-mark": string;
  "juuten-食事-食べ方-ゆっくり食べる": string;
  "juuten-食事-食べ方": string;
  "juuten-食事-食事時間-mark": string;
  "juuten-運動-mark": string;
  "juuten-運動-種類-mark": string;
  "juuten-運動-種類": string;
  "juuten-運動-時間": string;
  "juuten-運動-頻度": string;
  "juuten-運動-ほぼ毎日": string;
  "juuten-運動-息がはずむが会話が可能な強さ" : string;
  "juuten-運動-強度-脈拍": string;
  "juuten-運動-強度-その他": string;
  "juuten-運動-活動量-mark": string;
  "juuten-運動-活動量": string;
  "juuten-運動-注意事項-mark": string;
  "juuten-運動-注意事項": string;
  "juuten-たばこ-mark": string;
  "juuten-たばこ-非喫煙者-mark": string;
  "juuten-たばこ-禁煙・節煙の有効性-mark": string;
  "juuten-たばこ-禁煙の実施補法等-mark": string;
  "juuten-その他-mark": string;
  "juuten-その他-仕事-mark": string;
  "juuten-その他-余暇-mark": string;
  "juuten-その他-睡眠の確保-mark": string;
  "juuten-その他-減量-mark": string;
  "juuten-その他-家庭での計測-mark": string;
  "juuten-その他-その他-mark": string;
  "juuten-その他-その他": string;
  "kensa-採血日-月": string;
  "kensa-採血日-日": string;
  "kensa-総コレステロール-mark": string;
  "kensa-総コレステロール": string;
  "kensa-血糖-mark": string;
  "kensa-血糖-空腹時-mark": string;
  "kensa-血糖-随時-mark": string;
  "kensa-血糖-食後-mark": string;
  "kensa-血糖-食後": string;
  "kensa-中性脂肪-mark": string;
  "kensa-中性脂肪": string;
  "kensa-血糖-値": string;
  "kensa-ＨＤＬコレステロール-mark": string;
  "kensa-ＨＤＬコレステロール": string;
  "kensa-HbA1c": string;
  "kensa-ＬＤＬコレステロール-mark": string;
  "kensa-ＬＤＬコレステロール": string;
  "kensa-血液検査項目-その他-mark": string;
  "kensa-血液検査項目-その他": string;
  "kensa-栄養状態-mark": string;
  "kensa-その他-その他-mark": string;
  "医師氏名": string;
  "issue-times": string;
  "birthdate-age": string;
  "mokuhyou-目標達成状況": string;
  "juuten-食事-指導の必要なし-mark": string;
  "juuten-運動-指導の必要なし-mark": string;
  "患者署名省略-mark": string;
}

export function mkRyouyouKeikakushoData(): RyouyouKeikakushoData {
  return {
    "issue-year": "",
    "issue-month": "",
    "issue-day": "",
    "patient-name": "",
    "patient-sex-male": "",
    "patient-sex-female": "",
    "birthdate-gengou-meiji": "",
    "birthdate-gengou-taishou": "",
    "birthdate-gengou-shouwa": "",
    "birthdate-gengou-heisei": "",
    "birthdate-gengou-reiwa": "",
    "birthdate-nen": "",
    "birthdate-month": "",
    "birthdate-day": "",
    "patient-age": "",
    "disease-diabetes": "",
    "disease-hypertension": "",
    "disease-hyperlipidemia": "",
    "mokuhyou-体重-mark": "",
    "mokuhyou-体重": "",
    "mokuhyou-BMI-mark": "",
    "mokuhyou-BMI": "",
    "mokuhyou-BP-mark": "",
    "mokuhyou-BP": "",
    "mokuhyou-HbA1c-mark": "",
    "mokuhyou-HbA1c": "",
    "mokuhyou-達成目標": "",
    "mokuhyou-行動目標": "",
    "juuten-食事-mark": "",
    "juuten-食事-摂取量を適正にする-mark": "",
    "juuten-食事-食塩・調味料を控える-mark": "",
    "juuten-食事-食物繊維の摂取を増やす-mark": "",
    "juuten-食事-外食の際の注意事項-mark": "",
    "juuten-食事-外食の際の注意事項": "",
    "juuten-食事-油を使った料理の摂取を減らす-mark": "",
    "juuten-食事-その他-mark": "",
    "juuten-食事-節酒-mark": "",
    "juuten-食事-節酒": "",
    "juuten-食事-節酒-回": "",
    "juuten-食事-間食-mark": "",
    "juuten-食事-間食": "",
    "juuten-食事-間食-回": "",
    "juuten-食事-食べ方-mark": "",
    "juuten-食事-食べ方-ゆっくり食べる": "",
    "juuten-食事-食べ方": "",
    "juuten-食事-食事時間-mark": "",
    "juuten-運動-mark": "",
    "juuten-運動-種類-mark": "",
    "juuten-運動-種類": "",
    "juuten-運動-時間": "",
    "juuten-運動-頻度": "",
    "juuten-運動-ほぼ毎日": "",
    "juuten-運動-息がはずむが会話が可能な強さ": "",
    "juuten-運動-強度-脈拍": "",
    "juuten-運動-強度-その他": "",
    "juuten-運動-活動量-mark": "",
    "juuten-運動-活動量": "",
    "juuten-運動-注意事項-mark": "",
    "juuten-運動-注意事項": "",
    "juuten-たばこ-mark": "",
    "juuten-たばこ-非喫煙者-mark": "",
    "juuten-たばこ-禁煙・節煙の有効性-mark": "",
    "juuten-たばこ-禁煙の実施補法等-mark": "",
    "juuten-その他-mark": "",
    "juuten-その他-仕事-mark": "",
    "juuten-その他-余暇-mark": "",
    "juuten-その他-睡眠の確保-mark": "",
    "juuten-その他-減量-mark": "",
    "juuten-その他-家庭での計測-mark": "",
    "juuten-その他-その他-mark": "",
    "juuten-その他-その他": "",
    "kensa-採血日-月": "",
    "kensa-採血日-日": "",
    "kensa-総コレステロール-mark": "",
    "kensa-総コレステロール": "",
    "kensa-血糖-mark": "",
    "kensa-血糖-空腹時-mark": "",
    "kensa-血糖-随時-mark": "",
    "kensa-血糖-食後-mark": "",
    "kensa-血糖-食後": "",
    "kensa-中性脂肪-mark": "",
    "kensa-中性脂肪": "",
    "kensa-血糖-値": "",
    "kensa-ＨＤＬコレステロール-mark": "",
    "kensa-ＨＤＬコレステロール": "",
    "kensa-HbA1c": "",
    "kensa-ＬＤＬコレステロール-mark": "",
    "kensa-ＬＤＬコレステロール": "",
    "kensa-血液検査項目-その他-mark": "",
    "kensa-血液検査項目-その他": "",
    "kensa-栄養状態-mark": "",
    "kensa-その他-その他-mark": "",
    "医師氏名": "",
    "issue-times": "",
    "birthdate-age": "",
    "mokuhyou-目標達成状況": "",
    "juuten-食事-指導の必要なし-mark": "",
    "juuten-運動-指導の必要なし-mark": "",
    "患者署名省略-mark": "",
  };
}

